# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
# Add steps finally analyze code will be automated in CI/CD
# Final Check

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    
- task: CopyFiles@2
  inputs:
    Contents: '**/.war'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'snyk_demo'
    testType: 'app'
    monitorWhen: 'always'
    failOnIssues: true
    projectName: 'freeproject_three'
    testDirectory: '$(build.artifactstagingdirectory)'
    additionalArguments: '--all-projects')'
    artifact: 'warfile'
    publishLocation: 'pipeline'






